import Link from 'next/link';
import React from 'react';
export const metadata = {
  title: "Add-Product-page",
  description: "Generated by create next app",
};

const AddProductPage = () => {
  return (
    <div>
      add prod
     <Link href={`/Dashboard/add-product/${120}`}><button className='btn btn-primary'>Details</button></Link>
    </div>
  );
};

export default AddProductPage;