"use client"

import { ThemeContext } from '@/app/autProvider';
import Image from 'next/image';

import React, { useContext, useEffect, useState } from 'react';
export const metadata = {
  title: "MenageProduct page",
  description: "Generated by create next app",
};

const MenageProductPage  = () => {
 
  const { email, name } = useContext(ThemeContext)
  console.log('mean product',email,name);
  const [users, setUser] = useState([])
  useEffect(() => {
    fetch("https://jsonplaceholder.typicode.com/photos")
      .then((res) => res.json())
      .then((data) => setUser(data));

  }, [])
  console.log(users);
   
  return (
    <div className='container mx-auto'>
      <div className="flex justify-center">
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-10">
          {
            users.slice(0,100).map((user) => {
              const { thumbnailUrl, title, url,id } = user;
              return (
                <>
                  <div
                    loading="lazy"
                    key={id}
                    className="c w-[300px] h-[200px] p-4 "
                  >
                    <Image
                      width={200}
                      height={100}
                      src={thumbnailUrl}
                      alt="next image"
                    ></Image>
                    <h1>{title} </h1>
                  </div>
                </>
              );
            })

        }
        
        </div>
      
      </div>
 
       
    </div>
  );
};

export default MenageProductPage;