
import Footer from './Component/Footer/page'
import Header from './Component/Header/Header'
import ThemeProvider from './autProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Header></Header>

          {children}
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
