

'use client'
import Link from 'next/link';
import React, { useContext } from 'react';
import { ThemeContext } from '../autProvider';
export const metadata = {
  title: "Profile page",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  const { email, name } = useContext(ThemeContext)
  console.log('ProfilePage',email,name);
  return (
    <div>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident culpa
        similique pariatur veniam facilis soluta, delectus optio, est temporibus
        ipsam obcaecati enim quasi incidunt eaque amet! Cum minima quibusdam
        nulla.
      </p>
      <Link href={'/Ditails'}>
        {" "}
        <button className="btn btn-primary">Details</button>
      </Link>
    </div>
  );
};

export default ProfilePage;