import React from 'react';
import NavList from '../Component/Dash-Nav/NavList';
export const metadata = {
  title: "MenageProduct page",
  description: "Generated by create next app",
};

const DashboardLayout = ({children}) => {
  return (
    <div>
      <h1 className='text-3xl font-bold text-center mt-10'>This is Dashboard Layout</h1>
      <div className="main flex gap-10">
        <div className="leftNav">
          <NavList></NavList>
        </div>
        <div className="mains">
          {children}
        </div>
      </div>
    </div>
  );
};

export default DashboardLayout;