import React from 'react';
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardPage = () => {
  return (
    <div>
      This is DashboardPage
    </div>
  );
};

export default DashboardPage;